language: go

go:
  - 1.7

services:
  - mysql

test:
  adapter: mysql2
  database: persistent
  username: test
  encoding: utf8

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
  - make deps

script:
  - make test

after_success:
  - base <(curl -s https://codecov.io/bash)

notifications:
  slack:
    on_success: always
    on_failure: always
