language: go

os: linux

go:
  - 1.7

services:
  - mysql

test:
  adapter: mysql2
  database: persistent
  username: root
  encoding: utf8

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS persistent;'
  - make deps

script:
  - make test

after_success:
  - bash <(curl -s https://codecov.io/bash) -t 9e6ce202-72d2-49b8-8aef-f124229cae8d

notifications:
  slack:
    on_success: always
    on_failure: always
